# Generated by Django 4.0.2 on 2022-03-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('in_stock', models.BooleanField(default=False)),
            ],
        ),
    ]
